# Generated by Django 3.1.7 on 2021-02-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part_categories', '0001_initial'),
        ('manufacturer_parts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('manufacturer_part_qty', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_parts', related_query_name='supplier_part', to='part_categories.partcategory')),
                ('manufacturer_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_parts', related_query_name='supplier_part', to='manufacturer_parts.manufacturerpart')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_parts', to='organizations.organization')),
            ],
        ),
    ]
