# Generated by Django 3.1.7 on 2021-02-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part_categories', '__first__'),
        ('organizations', '__first__'),
        ('part_units', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_parts', related_query_name='manufacturer_part', to='part_categories.partcategory')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_parts', to='organizations.organization')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_parts', to='part_units.partunit')),
            ],
        ),
    ]
