# Generated by Django 3.1.7 on 2021-02-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logical_parts', '__first__'),
        ('manufacturer_parts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalPart2ManufacturerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_parts', related_query_name='manufacturer_part', to='logical_parts.logicalpart')),
                ('manufacturer_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logical_parts', related_query_name='logical_part', to='manufacturer_parts.manufacturerpart')),
            ],
        ),
    ]
